version: '3.9'
name: agsr-test

services:
  api:
    container_name: agsr-api
    build:
      context: ../
      dockerfile: AGSR.Api/Dockerfile
    environment:
      - ConnectionString=Host=db;Username=postgres;Password=postgres;Port=5432;Database=PatientsDb;
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api-db-network

  db:
    container_name: agsr-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=PatientsDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - api-db-network

networks:
  api-db-network:
    
volumes:
  db-data: